package tela;

import entidade.Usuario;
import javax.swing.JInternalFrame;

public class FrmJP extends javax.swing.JFrame {

    public static Usuario usuario;

    public FrmJP(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        // abre tela maximizada
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JDesktopPane();
        mnBarra = new javax.swing.JMenuBar();
        mnHome = new javax.swing.JMenu();
        mnCadastros = new javax.swing.JMenu();
        mniExercicio = new javax.swing.JMenuItem();
        mniAlimento = new javax.swing.JMenuItem();
        mniCompra = new javax.swing.JMenuItem();
        mniReacoesCorporais = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthBuilder");

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mnHome.setText("Home");
        mnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHomeMouseClicked(evt);
            }
        });
        mnBarra.add(mnHome);

        mnCadastros.setText("Cadastros");

        mniExercicio.setText("Exercício");
        mniExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExercicioActionPerformed(evt);
            }
        });
        mnCadastros.add(mniExercicio);

        mniAlimento.setText("Alimento");
        mniAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlimentoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniAlimento);

        mniCompra.setText("Compra");
        mniCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCompraActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCompra);

        mniReacoesCorporais.setText("Reações Corporais");
        mniReacoesCorporais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReacoesCorporaisActionPerformed(evt);
            }
        });
        mnCadastros.add(mniReacoesCorporais);

        mnBarra.add(mnCadastros);

        mnAjuda.setText("Ajuda");
        mnBarra.add(mnAjuda);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExercicioActionPerformed
        Object tela = getTela("Tela.IfrExercicio");
        if (tela == null) {
            tela = new IfrExercicio();
            pnHome.add((JInternalFrame) tela);
        }
        setActive((JInternalFrame) tela);
    }//GEN-LAST:event_mniExercicioActionPerformed

    private void mniAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlimentoActionPerformed
        Object tela = getTela("Tela.IfrAlimento");
        if (tela == null) {
            tela = new IfrAlimento();
            pnHome.add((JInternalFrame) tela);
        }
        setActive((JInternalFrame) tela);
    }//GEN-LAST:event_mniAlimentoActionPerformed

    private void mniCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCompraActionPerformed
        Object tela = getTela("Tela.IfrCompra");
        if (tela == null) {
            tela = new IfrCompra();
            pnHome.add((JInternalFrame) tela);
        }
        setActive((JInternalFrame) tela);
    }//GEN-LAST:event_mniCompraActionPerformed

    private void mniReacoesCorporaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReacoesCorporaisActionPerformed
        Object tela = getTela("Tela.IfrReacaoCorporal");
        if (tela == null) {
            tela = new IfrReacaoCorporal();
            pnHome.add((JInternalFrame) tela);
        }
        setActive((JInternalFrame) tela);
    }//GEN-LAST:event_mniReacoesCorporaisActionPerformed

    private void mnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHomeMouseClicked
        Object tela = getTela("Tela.IfrApresentacao");
        if (tela == null) {
            tela = new IfrApresentacao();
            pnHome.add((JInternalFrame) tela);
        }
        setActive((JInternalFrame) tela);
    }//GEN-LAST:event_mnHomeMouseClicked
    public Object getTela(String formName) {
        for (int i = 0; i < pnHome.getComponentCount(); i++) {
            if (pnHome.getComponents()[i].getClass().getName().equals(formName)) {
                return pnHome.getComponents()[i];
            }
        }
        return null;
    }

    public void setActive(JInternalFrame tela) {
        tela.setVisible(true);
        pnHome.moveToFront(tela);
        pnHome.setSelectedFrame(tela);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnHome;
    private javax.swing.JMenuItem mniAlimento;
    private javax.swing.JMenuItem mniCompra;
    private javax.swing.JMenuItem mniExercicio;
    private javax.swing.JMenuItem mniReacoesCorporais;
    private javax.swing.JDesktopPane pnHome;
    // End of variables declaration//GEN-END:variables
}
