/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author fabricio.pretto
 */
public class FrmJanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public FrmJanelaPrincipal() {
        initComponents();

        // abre tela maximizada
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPainel = new javax.swing.JDesktopPane();
        mnBarra = new javax.swing.JMenuBar();
        mnHome = new javax.swing.JMenu();
        mnCadastros = new javax.swing.JMenu();
        mniCadExe = new javax.swing.JMenuItem();
        mniCadAli = new javax.swing.JMenuItem();
        mniCadCompra = new javax.swing.JMenuItem();
        mniCadMachucado = new javax.swing.JMenuItem();
        mnValidacoes = new javax.swing.JMenu();
        mniExemplo = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthBuilder");

        javax.swing.GroupLayout DesktopPainelLayout = new javax.swing.GroupLayout(DesktopPainel);
        DesktopPainel.setLayout(DesktopPainelLayout);
        DesktopPainelLayout.setHorizontalGroup(
            DesktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        DesktopPainelLayout.setVerticalGroup(
            DesktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        mnHome.setText("Home");
        mnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHomeMouseClicked(evt);
            }
        });
        mnBarra.add(mnHome);

        mnCadastros.setText("Cadastros");

        mniCadExe.setText("Exercício");
        mniCadExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadExeActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadExe);

        mniCadAli.setText("Alimento");
        mniCadAli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadAliActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadAli);

        mniCadCompra.setText("Compra");
        mniCadCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadCompraActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadCompra);

        mniCadMachucado.setText("Reações Corporais");
        mniCadMachucado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadMachucadoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadMachucado);

        mnBarra.add(mnCadastros);

        mnValidacoes.setText("Validações");

        mniExemplo.setText("Exemplo");
        mniExemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExemploActionPerformed(evt);
            }
        });
        mnValidacoes.add(mniExemplo);

        mnBarra.add(mnValidacoes);

        mnAjuda.setText("Ajuda");
        mnBarra.add(mnAjuda);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopPainel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopPainel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExemploActionPerformed
        IfrValidacao ifrValidacao = new IfrValidacao();
        DesktopPainel.add(ifrValidacao);
        ifrValidacao.setVisible(true);
    }//GEN-LAST:event_mniExemploActionPerformed

    private void mniCadExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadExeActionPerformed
        IfrRegExercicio RegExe = new IfrRegExercicio();
        DesktopPainel.add(RegExe);
        RegExe.setVisible(true);
    }//GEN-LAST:event_mniCadExeActionPerformed

    private void mniCadAliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadAliActionPerformed
        IfrRegAlimento RegAli = new IfrRegAlimento();
        DesktopPainel.add(RegAli);
        RegAli.setVisible(true);
    }//GEN-LAST:event_mniCadAliActionPerformed

    private void mniCadCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadCompraActionPerformed
        IfrRegCompra RegCompra = new IfrRegCompra();
        DesktopPainel.add(RegCompra);
        RegCompra.setVisible(true);
    }//GEN-LAST:event_mniCadCompraActionPerformed

    private void mniCadMachucadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadMachucadoActionPerformed
        IfrRegReacaoCorporal RegMachucado = new IfrRegReacaoCorporal();
        DesktopPainel.add(RegMachucado);
        RegMachucado.setVisible(true);
    }//GEN-LAST:event_mniCadMachucadoActionPerformed

    private void mnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHomeMouseClicked
        IfrApresentacao ifrApresentacao = new IfrApresentacao();
        DesktopPainel.add(ifrApresentacao);
        ifrApresentacao.setVisible(true);
    }//GEN-LAST:event_mnHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPainel;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnHome;
    private javax.swing.JMenu mnValidacoes;
    private javax.swing.JMenuItem mniCadAli;
    private javax.swing.JMenuItem mniCadCompra;
    private javax.swing.JMenuItem mniCadExe;
    private javax.swing.JMenuItem mniCadMachucado;
    private javax.swing.JMenuItem mniExemplo;
    // End of variables declaration//GEN-END:variables
}
