package tela;

import entidade.Usuario;

public class FrmJP extends javax.swing.JFrame {
    public static Usuario usuario;
    public FrmJP(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        // abre tela maximizada
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPainel = new javax.swing.JDesktopPane();
        mnBarra = new javax.swing.JMenuBar();
        mnHome = new javax.swing.JMenu();
        mnCadastros = new javax.swing.JMenu();
        mniCadExe = new javax.swing.JMenuItem();
        mniCadAli = new javax.swing.JMenuItem();
        mniCadCompra = new javax.swing.JMenuItem();
        mniCadMachucado = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthBuilder");

        javax.swing.GroupLayout desktopPainelLayout = new javax.swing.GroupLayout(desktopPainel);
        desktopPainel.setLayout(desktopPainelLayout);
        desktopPainelLayout.setHorizontalGroup(
            desktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        desktopPainelLayout.setVerticalGroup(
            desktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mnHome.setText("Home");
        mnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHomeMouseClicked(evt);
            }
        });
        mnBarra.add(mnHome);

        mnCadastros.setText("Cadastros");

        mniCadExe.setText("Exercício");
        mniCadExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadExeActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadExe);

        mniCadAli.setText("Alimento");
        mniCadAli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadAliActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadAli);

        mniCadCompra.setText("Compra");
        mniCadCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadCompraActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadCompra);

        mniCadMachucado.setText("Reações Corporais");
        mniCadMachucado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadMachucadoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadMachucado);

        mnBarra.add(mnCadastros);

        mnAjuda.setText("Ajuda");
        mnBarra.add(mnAjuda);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadExeActionPerformed
        IfrRegExercicio RegExe = new IfrRegExercicio();
        desktopPainel.add(RegExe);
        RegExe.setVisible(true);
    }//GEN-LAST:event_mniCadExeActionPerformed

    private void mniCadAliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadAliActionPerformed
        IfrRegAlimento RegAli = new IfrRegAlimento();
        desktopPainel.add(RegAli);
        RegAli.setVisible(true);
    }//GEN-LAST:event_mniCadAliActionPerformed

    private void mniCadCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadCompraActionPerformed
        IfrRegCompra RegCompra = new IfrRegCompra();
        desktopPainel.add(RegCompra);
        RegCompra.setVisible(true);
    }//GEN-LAST:event_mniCadCompraActionPerformed

    private void mniCadMachucadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadMachucadoActionPerformed
        IfrRegReacaoCorporal RegMachucado = new IfrRegReacaoCorporal();
        desktopPainel.add(RegMachucado);
        RegMachucado.setVisible(true);
    }//GEN-LAST:event_mniCadMachucadoActionPerformed

    private void mnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHomeMouseClicked
        IfrApresentacao ifrApresentacao = new IfrApresentacao();
        desktopPainel.add(ifrApresentacao);
        ifrApresentacao.setVisible(true);
    }//GEN-LAST:event_mnHomeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPainel;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnHome;
    private javax.swing.JMenuItem mniCadAli;
    private javax.swing.JMenuItem mniCadCompra;
    private javax.swing.JMenuItem mniCadExe;
    private javax.swing.JMenuItem mniCadMachucado;
    // End of variables declaration//GEN-END:variables
}
