/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import com.sun.tools.javac.Main;
import dao.UsuarioDAO;
import entidade.Usuario;
import java.awt.Frame;
import java.io.InvalidObjectException;
import java.lang.System.Logger;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import util.FabricaDAO;
import util.Senha;
import util.Validacoes;

/**
 *
 * @author bbt-1
 */
public final class IfrLogin extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     *
     * @param parent
     * @param modal
     */
    public IfrLogin(java.awt.Frame parent, boolean modal) {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Painel = new javax.swing.JPanel();
        imagemHB = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblInfoLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        lblEsqueceuSenha = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        lblDica = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Painel.setBackground(new java.awt.Color(255, 255, 255));

        imagemHB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HealthBuilder224x224.jpg"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        lblTitulo.setText("HealthyBuilder");

        lblBemVindo.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        lblBemVindo.setText("Bem-vindo de volta!");

        lblInfoLogin.setFont(new java.awt.Font("High Tower Text", 0, 24)); // NOI18N
        lblInfoLogin.setText("Faça o login utilizando seu usuário e senha:");

        lblUsuario.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        tfUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        lblSenha.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        lblSenha.setText("Senha");

        pfSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        lblEsqueceuSenha.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        lblEsqueceuSenha.setForeground(new java.awt.Color(0, 0, 255));
        lblEsqueceuSenha.setText("Bá, esqueci minha senha");
        lblEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseClicked(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblPergunta.setFont(new java.awt.Font("High Tower Text", 1, 14)); // NOI18N
        lblPergunta.setText("Não possui uma conta?");

        btnRegistro.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        btnRegistro.setText("Registre-se");
        btnRegistro.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        lblDica.setFont(new java.awt.Font("High Tower Text", 1, 15)); // NOI18N
        lblDica.setText("Dica: não compartilhe sua senha com ninguém. Ela é sua identidade!");

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTitulo))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagemHB)))
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblInfoLogin))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblDica))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha)
                                    .addComponent(lblUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(pfSenha)))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(lblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEsqueceuSenha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagemHB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addComponent(lblBemVindo)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoLogin)
                        .addGap(18, 18, 18)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPergunta)
                                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(lblDica)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        IfrRegistroUsuario Registro = new IfrRegistroUsuario(new Frame(), true);
        Registro.setVisible(true);
        Registro.requestFocus();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void lblEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseClicked
        IfrEsqueceuSenha Queceu = new IfrEsqueceuSenha(new Frame(), true);
        Queceu.setVisible(true);
        Queceu.requestFocus();
    }//GEN-LAST:event_lblEsqueceuSenhaMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new FrmJanelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void changeProgramIcon(String icon) {
        setIconImage(new ImageIcon(getClass().getResource("../icons/" + icon)).getImage());
    }
    private void login() throws InvalidObjectException, NoSuchAlgorithmException {
        String username = tfUsuario.getText().trim();
        String password = new String(pfSenha.getPassword());

        try {
            Validacoes.notEmpty(0, username);
            Validacoes.notEmpty(1, password);

            Usuario user = FabricaDAO.getInstance(UsuarioDAO.class).getBy(username);
            Validacoes.notNull(2, user);

            Validacoes.isTrue(2, Senha.match(password, user.passwordHash));
            Main.currentUser = user;
            ((JFrame) stack.getHost()).dispose();

        } catch (Validacoes.InvalidField e) {
            Alert.showInfo((JFrame) stack.getHost(),
                    "Usuário ou senha inválidos, tente novamente!"
            );
        } catch (InvalidObjectException | NoSuchAlgorithmException ex) {
            Logger.error(getClass(), "error comparing hashes", ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel imagemHB;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblInfoLogin;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
